library(rmarkdown)

render("src/w1.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w2.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w3.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w4.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w5.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w6.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w7.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w8.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w9.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w10.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w12.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w13.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w14.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w15.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
render("src/w16.Rmd", "beamer_presentation", output_dir = normalizePath(getwd()))
