---
title: "Some Simple `leaflet` Examples"
author: "JJ Chen"
date: "April 3, 2015"
output:
  html_document:
    css: style.css
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(dev = 'pdf', comment=NA, warning=FALSE, message=FALSE)
```

## Base Maps
```{r}
# install.packages("devtools")
# devtools::install_github('rstudio/leaflet')
library(leaflet)

# create a html widget using `leaflet()`, and then add tile layers
leaflet() %>%
    addTiles()

# Another example
# Find the longitude and latitude data for some location
ggmap::geocode("UIC east campus Library")

# Set the window
leaflet() %>%
    addTiles() %>%
    setView(-87.65038, 41.87172, zoom = 17)
```

## Dot Distribution Maps
```{r}
# Add some points
points <- data.frame(long = rnorm(100, mean = -100, sd = 2),
                     lat = rnorm(100, mean = 40, sd = 2))
leaflet() %>%
    addTiles() %>%
    addCircles(data = points)
```

## Choropleth Maps
```{r}
# Prepare boundry data
library(maps)
statePolygons = map("state", fill = TRUE, plot = FALSE)

# Prepare a variable of interest; here I just make up some data
statePolygons$value = rnorm(63) 

# Prepare a vector of color according to the variable
pal = colorQuantile("YlGn", NULL, n = 5)
vecColor = pal(statePolygons$value)

# Draw a Choropleth
leaflet(data = statePolygons) %>% 
    addTiles() %>%
    addPolygons(fillColor = vecColor,
                stroke = F)
```

